AllCops:
  Exclude:
    - db/migrate/**/*
    - db/schema.rb
    - config/**/*
    - script/**/*
    - bin/**/*
    - test/**/*
    - app/admin/**/*
    - app/channels/**/*
    - app/jobs/**/*
    - node_modules/**/*
    - Gemfile
    - Rakefile
    - config.ru

require:
  - rubocop-rails

Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/InlineComment:
  Enabled: false

Layout/LineLength:
  Max: 100
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Lint/UnusedBlockArgument:
  AutoCorrect: false

Lint/UnusedMethodArgument:
  AutoCorrect: false
  Exclude:
    - 'app/models/**'

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
