default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USER'] || 'firearm_depot' %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>

development:
  <<: *default
  database: firearm_depot_development

test:
  <<: *default
  database: firearm_depot_test

production:
  <<: *default
  database: firearm_depot_production
  username: firearm_depot
  password: <%= ENV["FIREARM_DEPOT_DATABASE_PASSWORD"] %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
